# Generated by Django 4.1.2 on 2022-10-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_artiste_age_alter_artiste_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='songs',
            new_name='song',
        ),
    ]
